#! /bin/sh

###---Autostart---###
startup &
###---Monitor---###
bspc monitor -d I II III IV V VI VII VIII IX X

###---Gaaps---###
bspc config border_width         3
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

###--Rule---###
bspc rule -a Zathura state=tiled

###---Global Settings---###
bspc config click_to_focus false
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer true

# Border Colors
bspc config normal_border_color	"#4C566A"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#5E81AC"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#BF616A"
